export const GUESSING_GAME = 'GUESSING_GAME';
export const GUESSING_VOTING = 'GUESSING_VOTING';
export const GUESSING_WAITING = 'GUESSING_WAITING';
export const GUESSING_ENDED = 'GUESSING_ENDED';

export const FULL_SHOW_WAITING = 'FULL_SHOW_WAITING';
export const FULL_SHOW_VOTING = 'FULL_SHOW_VOTING';
export const ANNOUNCEMENT = 'ANNOUNCEMENT';
