export const ESTIMATION_GAME = 'ESTIMATION_GAME';
export const ESTIMATION_VOTING = 'ESTIMATION_VOTING';
export const ESTIMATION_WAITING = 'ESTIMATION_WAITING';
export const ESTIMATION_ENDED = 'ESTIMATION_ENDED';

export const FULL_SHOW_WAITING = 'FULL_SHOW_WAITING';
export const FULL_SHOW_VOTING = 'FULL_SHOW_VOTING';
export const ANNOUNCEMENT = 'ANNOUNCEMENT';
